dist: xenial

language: python
python:
    - "3.7"
install:
    - "pip install -r requirements.txt"

script:
    - "nosetests tests --nologcapture --with-coverage --cover-inclusive --cover-erase --cover-package ."
    - "coverage report -m --omit roistats/atlases/__init__.py"
after_success:
    - coveralls
